gateway:
  app:
    name: p2p-listings
  gateway:
    name: http-gw
  routes:
    - matchPath: /api/p2p/listings
      replacePath: /api/listings
      backend:
        serviceName: p2p-listings-service
        servicePort: 80

monitoring:
  services:
    - name: p2p-listings-monitor
      app: p2p-listings-service
      port: "api"
      interval: 60s