
name: p2p-listings
replicaCount: 1
image:
  repository: registry.digitalocean.com/clutchbids-registry/p2p-listings
  tag: latest
imagePullSecrets:
  name: clutchbids-registry
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

config:
  NODE_ENV: prod

probes:
  pathPrefix: /api/listings/health
  port: 3000

# Startup probe configuration
startupProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 30 

# Readiness probe configuration
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3