name: scraper-openlane
replicaCount: 1
image:
  repository: registry.digitalocean.com/clutchbids-registry/scraper-openlane
  tag: latest
imagePullSecrets:
  name: clutchbids-registry
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

config:
  NODE_ENV: dev


# Startup probe configuration
startupProbe:
  enabled: false
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 30 

# Readiness probe configuration
readinessProbe:
  enabled: false
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3