name: openlane-scraper
replicaCount: 1
image:
  repository: registry.digitalocean.com/clutchbids-registry/openlane-scraper
  tag: latest
imagePullSecrets:
  name: clutchbids-registry
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

config:
  NODE_ENV: prod
