
name: best-value-auctions
replicaCount: 1
image:
  repository: registry.digitalocean.com/clutchbids-registry/best-value-auctions
imagePullSecrets:
  name: clutchbids-registry
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

config:
  NODE_ENV: dev

probes:
  pathPrefix: /api/health
  port: 3000

# Startup probe configuration
startupProbe:
  enabled: false
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 30 

# Readiness probe configuration
readinessProbe:
  enabled: false
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3